In [ ]:
#Task 1
class Customer:
  def __init__(self,name):
    self.name=name
  def greet(self,n=None):
    if n==None:
      print('Hello!')
    else:
      print('Hello',n+'!')
  def purchase(self,*t):
    print(f'{self.name}, you purchased {len(t)} item(s):')
    for i in t:
      print(i)
customer_1 = Customer("Sam")
customer_1.greet()
customer_1.purchase("chips", "chocolate", "orange juice")
print("-----------------------------")
customer_2 = Customer("David")
customer_2.greet("David")
customer_2.purchase("orange juice")

Hello!
Sam, you purchased 3 item(s):
chips
chocolate
orange juice
-----------------------------
Hello David!
David, you purchased 1 item(s):
orange juice

In [ ]:
#Task 2
class Panda:
  def __init__(self,name,gender,age):
    self.name=name
    self.gender=gender
    self.age=age
  def sleep(self,s=None):
    self.sleep=s
    if self.sleep==None:
      return(f"{self.name}'s duration is unknown thus should have only bamboo leaves")
    if 3<=self.sleep<=5:
      return(f'{self.name} sleeps {self.sleep} hours daily and should have Mixed Veggies')
    if 6<=self.sleep<=8:
      return(f'{self.name} sleeps {self.sleep} hours daily and should have Eggplant & Tofu')
    if 9<=self.sleep<=11:
      return(f'{self.name} sleeps {self.sleep} hours daily and should have Broccoli Chicken')
panda1 = Panda("Kunfu","Male", 5)
panda2=Panda("Pan Pan","Female",3)
panda3=Panda("Ming Ming","Female",8)
print("{} is a {} Panda Bear who is {} years old".format(panda1.name,panda1.gender,panda1.age))
print("{} is a {} Panda Bear who is {} years old".format(panda2.name,panda2.gender,panda2.age))
print("{} is a {} Panda Bear who is {} years old".format(panda3.name,panda3.gender,panda3.age))
print("===========================")
print(panda2.sleep(10))
print(panda1.sleep(4))
print(panda3.sleep())

Kunfu is a Male Panda Bear who is 5 years old
Pan Pan is a Female Panda Bear who is 3 years old
Ming Ming is a Female Panda Bear who is 8 years old
===========================
Pan Pan sleeps 10 hours daily and should have Broccoli Chicken
Kunfu sleeps 4 hours daily and should have Mixed Veggies
Ming Ming's duration is unknown thus should have only bamboo leaves

In [ ]:
#Task 3
class Cat:
  def __init__(self,colour=None,activity=None):
    if colour==None:
      self.colour='White'
    else:
      self.colour=colour
    if activity==None:
      self.activity='sitting'
    else:
      self.activity=activity
  def printCat(self):
    print(f'{self.colour} cat is {self.activity}')
  def changeColor(self,x):
    self.colour=x
c1 = Cat()
c2 = Cat("Black")
c3 = Cat("Brown", "jumping")
c4 = Cat("Red", "purring")
c1.printCat()
c2.printCat()
c3.printCat()
c4.printCat()
c1.changeColor("Blue")
c3.changeColor("Purple")
c1.printCat()
c3.printCat()

White cat is sitting
Black cat is sitting
Brown cat is jumping
Red cat is purring
Blue cat is sitting
Purple cat is jumping

In [ ]:
#Task 4
class Student:
  def __init__(self,name='default student'):
    self.name=name
  def quizcalc(self,n1=0,n2=0,n3=0):
    self.marks=(n1+n2+n3)/3
  def printdetail(self):
    print('Hello',self.name)
    print('Your average quiz score is',self.marks)
s1 = Student()
s1.quizcalc(10)
print('--------------------------------')
s1.printdetail()
s2 = Student('Harry')
s2.quizcalc(10,8)
print('--------------------------------')
s2.printdetail()
s3 = Student('Hermione')
s3.quizcalc(10,9,10)
print('--------------------------------')
s3.printdetail()

--------------------------------
Hello default student
Your average quiz score is 3.3333333333333335
--------------------------------
Hello Harry
Your average quiz score is 6.0
--------------------------------
Hello Hermione
Your average quiz score is 9.666666666666666

In [ ]:
#Task 5
class Student:
  def __init__(self,name,id,dept='CSE'):
    self.name=name
    self.id=id
    self.dept=dept
  def dailyEffort(self,hours):
    self.hours=hours
    if self.hours<=2:
      self.sugg='Should give more effort!'
    elif self.hours<=4:
      self.sugg='Keep up the good work!'
    else:
      self.sugg='Excellent! Now motivate others.'
  def printDetails(self):
    print('Name:',self.name)
    print('ID:',self.id)
    print('Department:',self.dept)
    print('Daily Effort:',self.hours,'hour(s)')
    print('Suggestion:',self.sugg)
harry = Student('Harry Potter', 123)
harry.dailyEffort(3)
harry.printDetails()	
print('========================')
john = Student("John Wick", 456, "BBA")
john.dailyEffort(2)
john.printDetails()
print('========================')
naruto = Student("Naruto Uzumaki", 777, "Ninja")
naruto.dailyEffort(6)
naruto.printDetails()

Name: Harry Potter
ID: 123
Department: CSE
Daily Effort: 3 hour(s)
Suggestion: Keep up the good work!
========================
Name: John Wick
ID: 456
Department: BBA
Daily Effort: 2 hour(s)
Suggestion: Should give more effort!
========================
Name: Naruto Uzumaki
ID: 777
Department: Ninja
Daily Effort: 6 hour(s)
Suggestion: Excellent! Now motivate others.

In [ ]:
#Task 6
class Patient:
  def __init__(self,name,age):
    self.name=name
    self.age=age
    self.symptom=''
  def add_Symptom(self,*s):
    for i in s:
      self.symptom+=i+', '
  def printPatientDetail(self):
    print('Name:',self.name)
    print('Age:',self.age)
    print('Symptoms:',self.symptom[:-2])
p1 = Patient("Thomas", 23)
p1.add_Symptom("Headache")
p2 = Patient("Carol", 20)
p2.add_Symptom("Vomiting", "Coughing")
p3 = Patient("Mike", 25)
p3.add_Symptom("Fever", "Headache", "Coughing")
print("=========================")
p1.printPatientDetail()
print("=========================")
p2.printPatientDetail()
print("=========================")
p3.printPatientDetail()

=========================
Name: Thomas
Age: 23
Symptoms: Headache
=========================
Name: Carol
Age: 20
Symptoms: Vomiting, Coughing
=========================
Name: Mike
Age: 25
Symptoms: Fever, Headache, Coughing

In [ ]:
#Task 7
class Match:
  def __init__(self,teams):
    x=teams.split('-')
    self.bat=x[0]
    self.bowl=x[1]
    print('5..4..3..2..1.. Play !!!')
    self.run=0
    self.over=0
    self.wicket=0
  def add_run(self,n):
    self.run+=n
  def add_over(self,n):
    if self.over+n<=5:
      self.over+=n
    else:
      print(f'Warning! Cannot add {n} over/s (5 over match)')
  def add_wicket(self,n):
    if self.wicket+n<=10:
      self.wicket+=n
  def print_scoreboard(self):
    return f'Batting Team: {self.bat}\nBowling Team: {self.bowl}\nTotal Runs: {self.run} Wickets: {self.wicket} Overs: {self.over}'
match1 = Match("Rangpur Riders-Cumilla Victorians")
print("=========================")
match1.add_run(4)
match1.add_run(6)
match1.add_over(1)
print(match1.print_scoreboard())
print("=========================")
match1.add_over(5)
print("=========================")
match1.add_wicket(1)
print(match1.print_scoreboard())

5..4..3..2..1.. Play !!!
=========================
Batting Team: Rangpur Riders
Bowling Team: Cumilla Victorians
Total Runs: 10 Wickets: 0 Overs: 1
=========================
Warning! Cannot add 5 over/s (5 over match)
=========================
Batting Team: Rangpur Riders
Bowling Team: Cumilla Victorians
Total Runs: 10 Wickets: 1 Overs: 1

In [ ]:
#Task 8
class ParcelKoro:
  def __init__(self,name='No name set',weight=0):
    self.name=name
    self.product_weight=weight
  def calculateFee(self,place=None):
    if self.product_weight==0:
      self.total=0
    elif place==None:
      self.total=(self.product_weight*20)+50
    else:
      self.total=(self.product_weight*20)+100
  def printDetails(self):
    print('Customer Name:',self.name)
    print('Product Weight:',self.product_weight)
    print('Total fee:',self.total)
print("**********************")
p1 = ParcelKoro()
p1.calculateFee()
p1.printDetails()
print("**********************")
p2 = ParcelKoro('Bob The Builder')
p2.calculateFee()
p2.printDetails()
print("----------------------------")
p2.product_weight = 15
p2.calculateFee()
p2.printDetails()
print("**********************")
p3 = ParcelKoro('Dora The Explorer', 10)
p3.calculateFee('Dhanmondi')
p3.printDetails()

**********************
Customer Name: No name set
Product Weight: 0
Total fee: 0
**********************
Customer Name: Bob The Builder
Product Weight: 0
Total fee: 0
----------------------------
Customer Name: Bob The Builder
Product Weight: 15
Total fee: 350
**********************
Customer Name: Dora The Explorer
Product Weight: 10
Total fee: 300

In [ ]:
#Task 9
class Batsman:
  def __init__(self,*t):
    if len(t)==2:
      self.name='New Batsman'
      self.runs=t[0]
      self.balls=t[1]
    else:
      self.name=t[0]
      self.runs=t[1]
      self.balls=t[2]
  def printCareerStatistics(self):
    print('Name:',self.name)
    print('Runs Scored:',self.runs,', Balls Faced:',self.balls)
  def battingStrikeRate(self):
    return self.runs/self.balls*100
  def setName(self,name):
    self.name=name
b1 = Batsman(6101, 7380)
b1.printCareerStatistics()
print("============================")
b2 = Batsman("Liton Das", 678, 773)
b2.printCareerStatistics()
print("----------------------------")
print(b2.battingStrikeRate())
print("============================")
b1.setName("Shakib Al Hasan")
b1.printCareerStatistics()
print("----------------------------")
print(b1.battingStrikeRate())

Name: New Batsman
Runs Scored: 6101 , Balls Faced: 7380
============================
Name: Liton Das
Runs Scored: 678 , Balls Faced: 773
----------------------------
87.71021992238033
============================
Name: Shakib Al Hasan
Runs Scored: 6101 , Balls Faced: 7380
----------------------------
82.66937669376694

In [ ]:
#Task 10
class EPL_Team:
  def __init__(self,name,song='No Slogan',title=0):
    self.name=name
    self.song=song
    self.title=title
  def increaseTitle(self,n=1):
    self.title+=n
  def changeSong(self,s):
    self.song=s
  def showClubInfo(self):
    return f'Name: {self.name}\nSong: {self.song}\nTotal No of title: {self.title}'
manu = EPL_Team('Manchester United', 'Glory Glory Man United')
chelsea = EPL_Team('Chelsea')
print('===================')
print(manu.showClubInfo())
print('##################')
manu.increaseTitle()
print(manu.showClubInfo())
print('===================')
print(chelsea.showClubInfo())
chelsea.changeSong('Keep the blue flag flying high')
print(chelsea.showClubInfo())

===================
Name: Manchester United
Song: Glory Glory Man United
Total No of title: 0
##################
Name: Manchester United
Song: Glory Glory Man United
Total No of title: 1
===================
Name: Chelsea
Song: No Slogan
Total No of title: 0
Name: Chelsea
Song: Keep the blue flag flying high
Total No of title: 0

In [ ]:
#Task 11
class Author:
  def __init__(self,name='Default',*books):
    self.name=name
    self.booklist=[]
    for i in books:
      self.booklist.append(i)
  def addBooks(self,*books):
    for i in books:
      self.booklist.append(i)
  def changeName(self,name):
    self.name=name
  def printDetails(self):
    print('Author Name:',self.name)
    print('--------')
    print('List of Books:')
    for i in self.booklist:
      print(i)
auth1 = Author('Humayun Ahmed')
auth1.addBooks('Deyal', 'Megher Opor Bari')
auth1.printDetails()
print("===================")
auth2 = Author()
print(auth2.name)
auth2.changeName('Mario Puzo')
auth2.addBooks('The Godfather', 'Omerta', 'The Sicilian')
print("===================")
auth2.printDetails()
print("===================")
auth3 = Author('Paolo Coelho', 'The Alchemist', 'The Fifth Mountain')
auth3.printDetails()

Author Name: Humayun Ahmed
--------
List of Books:
Deyal
Megher Opor Bari
===================
Default
===================
Author Name: Mario Puzo
--------
List of Books:
The Godfather
Omerta
The Sicilian
===================
Author Name: Paolo Coelho
--------
List of Books:
The Alchemist
The Fifth Mountain

In [ ]:
#Task 12
class TaxiLagbe:
  def __init__(self,taxi_no,city):
    self.taxi_no=taxi_no
    self.city=city
    self.passengers=[]
    self.fare=0
    self.passengernames=''
  def addPassenger(self,*n):
    if len(self.passengers)!=4:
      for i in n:
          x=i.split('_')
          print(f'Dear {x[0]}! Welcome to TaxiLagbe.')
          self.fare+=int(x[1])
          self.passengers.append(x[0])
          self.passengernames+=x[0]+', '
    else:
      print('Taxi Full! No more passengers can be added.')
  def printDetails(self):
    print(f'Trip info for Taxi number: {self.taxi_no}')
    print(f'This taxi can cover only {self.city} area.')
    print(f'Total passengers: {len(self.passengers)}')
    print(f'Passenger lists: {self.passengernames[:-2]}')
    print(f'Total collected fare: {self.fare} Taka')
taxi1 = TaxiLagbe('1010-01', 'Dhaka')
print('-------------------------------')
taxi1.addPassenger('Walker_100', 'Wood_200')
taxi1.addPassenger('Matt_100')
taxi1.addPassenger('Wilson_105')
print('-------------------------------')
taxi1.printDetails()
print('-------------------------------')
taxi1.addPassenger('Karen_200')
print('-------------------------------')
taxi1.printDetails()
print('-------------------------------')
taxi2 = TaxiLagbe('1010-02', 'Khulna')
taxi2.addPassenger('Ronald_115')
taxi2.addPassenger('Parker_215')
print('-------------------------------')
taxi2.printDetails()

-------------------------------
Dear Walker! Welcome to TaxiLagbe.
Dear Wood! Welcome to TaxiLagbe.
Dear Matt! Welcome to TaxiLagbe.
Dear Wilson! Welcome to TaxiLagbe.
-------------------------------
Trip info for Taxi number: 1010-01
This taxi can cover only Dhaka area.
Total passengers: 4
Passenger lists: Walker, Wood, Matt, Wilson
Total collected fare: 505 Taka
-------------------------------
Taxi Full! No more passengers can be added.
-------------------------------
Trip info for Taxi number: 1010-01
This taxi can cover only Dhaka area.
Total passengers: 4
Passenger lists: Walker, Wood, Matt, Wilson
Total collected fare: 505 Taka
-------------------------------
Dear Ronald! Welcome to TaxiLagbe.
Dear Parker! Welcome to TaxiLagbe.
-------------------------------
Trip info for Taxi number: 1010-02
This taxi can cover only Khulna area.
Total passengers: 2
Passenger lists: Ronald, Parker
Total collected fare: 330 Taka

In [ ]:
#Task 13
class Account:
  def __init__(self,name='Default Account',balance=0.0):
    self.name=name
    self.balance=balance
  def details(self):
    return f'{self.name}\n{self.balance}'
  def withdraw(self,withdraw):
    if self.balance-withdraw<0:
      print('Sorry, Withdraw unsuccessful! The account balance after deducting withdraw amount is equal to or less than minimum.')
    else:
      self.balance-=withdraw
      print('Withdraw successful! New balance is:',self.balance)
a1 = Account()
print(a1.details())
print("------------------------")
a1.name = "Oliver"
a1.balance = 10000.0
print(a1.details())
print("------------------------")
a2 = Account("Liam")
print(a2.details())
print("------------------------")
a3 = Account("Noah",400)
print(a3.details())
print("------------------------")
a3.withdraw(6930)
print("------------------------")
a2.withdraw(600)
print("------------------------")
a1.withdraw(6929)

Default Account
0.0
------------------------
Oliver
10000.0
------------------------
Liam
0.0
------------------------
Noah
400
------------------------
Sorry, Withdraw unsuccessful! The account balance after deducting withdraw amount is equal to or less than minimum.
------------------------
Sorry, Withdraw unsuccessful! The account balance after deducting withdraw amount is equal to or less than minimum.
------------------------
Withdraw successful! New balance is: 3071.0

In [ ]:
#Task 13
class Account:
  def __init__(self,name='Default Account',balance=0.0):
    self.name=name
    self.balance=balance
  def details(self):
    return f'{self.name}\n{self.balance}'
  def withdraw(self,withdraw):
    if self.balance-withdraw<=3070:
      print('Sorry, Withdraw unsuccessful! The account balance after deducting withdraw amount is equal to or less than minimum.')
    else:
      self.balance-=withdraw
      print('Withdraw successful! New balance is:',self.balance)
a1 = Account()
print(a1.details())
print("------------------------")
a1.name = "Oliver"
a1.balance = 10000.0
print(a1.details())
print("------------------------")
a2 = Account("Liam")
print(a2.details())
print("------------------------")
a3 = Account("Noah",400)
print(a3.details())
print("------------------------")
a1.withdraw(6930)
print("------------------------")
a2.withdraw(600)
print("------------------------")
a1.withdraw(6929)

Default Account
0.0
------------------------
Oliver
10000.0
------------------------
Liam
0.0
------------------------
Noah
400
------------------------
Sorry, Withdraw unsuccessful! The account balance after deducting withdraw amount is equal to or less than minimum.
------------------------
Sorry, Withdraw unsuccessful! The account balance after deducting withdraw amount is equal to or less than minimum.
------------------------
Withdraw successful! New balance is: 3071.0

In [ ]:
#Task 14
class StudentDatabase:
  def __init__(self,name,id):
    self.name=name
    self.id=id
    self.grades={}
  def calculateGPA(self,cl,sem):
    l=[]
    s=0
    d={}
    for i in cl:
      x=i.split(': ')
      l.append(x[0])
      s+=float(x[1])
    d[tuple(l)]=round((s/len(l)),2)
    self.grades[sem]=d
  def printDetails(self):
    print('Name:',self.name)
    print('ID:',self.id)
    for i,j in self.grades.items():
      print(f'Courses taken in {i}:')
      for k,l in j.items():
        for m in k:
          print(m)
        print('GPA:',l)
s1 = StudentDatabase('Pietro', '10101222')
s1.calculateGPA(['CSE230: 4.0', 'CSE220: 4.0', 'MAT110: 4.0'], 'Summer2020')
s1.calculateGPA(['CSE250: 3.7', 'CSE330: 4.0'], 'Summer2021')
print(f'Grades for {s1.name}\n{s1.grades}')
print('------------------------------------------------------')
s1.printDetails()
s2 = StudentDatabase('Wanda', '10103332')
s2.calculateGPA(['CSE111: 3.7', 'CSE260: 3.7', 'ENG101: 4.0'], 'Summer2022')
print('------------------------------------------------------')
print(f'Grades for {s2.name}\n{s2.grades}')
print('------------------------------------------------------')
s2.printDetails()

Grades for Pietro
{'Summer2020': {('CSE230', 'CSE220', 'MAT110'): 4.0}, 'Summer2021': {('CSE250', 'CSE330'): 3.85}}
------------------------------------------------------
Name: Pietro
ID: 10101222
Courses taken in Summer2020:
CSE230
CSE220
MAT110
GPA: 4.0
Courses taken in Summer2021:
CSE250
CSE330
GPA: 3.85
------------------------------------------------------
Grades for Wanda
{'Summer2022': {('CSE111', 'CSE260', 'ENG101'): 3.8}}
------------------------------------------------------
Name: Wanda
ID: 10103332
Courses taken in Summer2022:
CSE111
CSE260
ENG101
GPA: 3.8

In [ ]:
#Task 15
class FinalT6A:
    def __init__(self, x, p):
        self.temp, self.sum, self.y = 4, 0, 1
        self.temp += 1
        self.y = self.temp - p
        self.sum = self.temp + x
        print(x, self.y, self.sum)
    def methodA(self):
        x = 0
        y = 0
        y = y + self.y
        x = self.y + 2 + self.temp
        self.sum = x + y + self.methodB(self.temp, y)
        print(x, y, self.sum)
    def methodB(self, temp, n):
        x = 0
        temp += 1
        self.y = self.y + temp
        x = x + 3 + n
        self.sum = self.sum + x + self.y
        print(x, self.y, self.sum)
        return self.sum
q1 = FinalT6A(2,1)
q1.methodA()
q1.methodA()

2 4 7
7 10 24
11 4 39
13 16 68
17 10 95

In [ ]:
#Task 16
class Quiz3A:
    def __init__(self, k = None):
        self.temp, self.sum, self.y = 4, 0, 0
        if k != None:
            self.temp += 1
            self.temp = self.temp
            self.sum = self.temp + k
            self.y = self.sum - 1
        else:
            self.y = self.temp - 1
            self.sum = self.temp + 1
            self.temp += 2    
    def methodB(self, m, n):
        x = 0
        self.temp += 1
        self.y = self.y + m + (self.temp)
        x = x + 2 + n
        self.sum = self.sum + x + self.y
        print(x, self.y, self.sum)
        return self.sum
a1 = Quiz3A()
a1.methodB(1,2)
a2 = Quiz3A(3)
a2.methodB(2,4)
a1.methodB(2,1)
a2.methodB(1,3)

4 11 20
6 15 29
3 21 44
5 23 57

57

In [ ]:
#Task 17
class Test5:
  def __init__(self):
      self.sum = 0
      self.y = 0
  def methodA(self):   
      x=y=k=0
      msg = [5]  
      while (k < 2):
          y += msg[0]     
          x = y + self.methodB(msg, k)
          self.sum = x + y + msg[0]
          print(x ," " , y, " " , self.sum)
          k+=1 
  def methodB(self, mg2, mg1):
        x = 0
        self.y += mg2[0]
        x = x + 3 + mg1
        self.sum += x + self.y
        mg2[0] = self.y + mg1
        mg1 += x + 2
        print(x , " " ,self.y, " " , self.sum)
        return mg1
t1 = Test5()
t1.methodA()
t1.methodA()
t1.methodA()

3   5   8
10   5   20
4   10   34
17   10   38
3   15   56
10   5   30
4   30   64
27   20   78
3   35   116
10   5   50
4   70   124
47   40   158

In [ ]:
#Task 18
class Test4:
    def __init__(self):
        self.sum, self.y = 0, 0
    def methodA(self):
        x, y = 0, 0
        msg = [0]
        msg[0] = 5
        y = y + self.methodB(msg[0])
        x = y + self.methodB(msg, msg[0])
        self.sum = x + y + msg[0]
        print(x, y, self.sum)
    def methodB(self, *args):
        if len(args) == 1:
            mg1 = args[0]
            x, y = 0, 0
            y = y + mg1
            x = x + 33 + mg1
            self.sum = self.sum + x + y
            self.y = mg1 + x + 2
            print(x, y, self.sum)
            return y
        else:
            mg2, mg1 = args
            x = 0
            self.y = self.y + mg2[0]
            x = x + 33 + mg1
            self.sum = self.sum + x + self.y
            mg2[0] = self.y + mg1
            mg1 = mg1 + x + 2
            print(x, self.y, self.sum)
            return self.sum
t3 = Test4()
t3.methodA()
t3.methodA()
t3.methodA()
t3.methodA()

38 5 43
38 50 131
136 5 196
38 5 239
38 50 327
332 5 392
38 5 435
38 50 523
528 5 588
38 5 631
38 50 719
724 5 784

In [ ]:
#Task 19
class msgClass:
    def __init__(self):
        self.content = 0 
class Q5:
    def __init__(self):
        self.sum = 1
        self.x = 2
        self.y = 3 
    def methodA(self):
        x, y = 1, 1
        msg = []
        myMsg = msgClass()
        myMsg.content = self.x
        msg.append(myMsg)
        msg[0].content = self.y + myMsg.content
        self.y = self.y + self.methodB(msg[0])
        y = self.methodB(msg[0]) + self.y
        x = y + self.methodB(msg[0], msg)
        self.sum = x + y + msg[0].content
        print(x," ", y," ", self.sum)    
    def methodB(self, mg1, mg2 = None):
        if mg2 == None:
            x, y = 5, 6
            y = self.sum + mg1.content
            self.y = y + mg1.content
            x = self.x + 7 +mg1.content
            self.sum = self.sum + x + y
            self.x = mg1.content + x +8
            print(x, " ", y," ", self.sum)
            return y
        else:
            x = 1
            self.y += mg2[0].content
            mg2[0].content = self.y + mg1.content
            x = x + 4 + mg1.content
            self.sum += x + self.y
            mg1.content = self.sum - mg2[0].content
            print(self.x, " ",self.y," ", self.sum)
            return self.sum
q = Q5()
q.methodA()

14   6   21
39   26   86
52   36   168
225   57   409

In [ ]:
#Task 20
class Student:
  def __init__(self,name=None,dept=None):
    self.name=name
    self.dept=dept
    if name==None and dept==None:
      print('Student name and department need to be set')
    elif dept==None:
      print(f'Department for {self.name} needs to be set')
    else:
      print(f'{self.name} is from {self.dept} department')
  def update_name(self,name):
    self.name=name
  def update_department(self,dept):
    self.dept=dept
  def enroll(self,*c):
    self.courses=[]
    for i in c:
      self.courses.append(i)
  def printDetail(self):
    x=''
    for i in self.courses:
      x+=i+', '
    print('Name:',self.name)
    print('Department:',self.dept)
    print(f'Bob enrolled in {len(self.courses)} course(s):')
    print(x[:-2])
s1 = Student()
print("=========================")
s2 = Student("Carol")
print("=========================")
s3 = Student("Jon", "EEE")
print("=========================")
s1.update_name("Bob")
s1.update_department("CSE")
s2.update_department("BBA")
s1.enroll("CSE110", "MAT110", "ENG091")
s2.enroll("BUS101")
s3.enroll("MAT110", "PHY111")
print("###########################")
s1.printDetail()
print("=========================")
s2.printDetail()
print("=========================")
s3.printDetail()

Student name and department need to be set
=========================
Department for Carol needs to be set
=========================
Jon is from EEE department
=========================
###########################
Name: Bob
Department: CSE
Bob enrolled in 3 course(s):
CSE110, MAT110, ENG091
=========================
Name: Carol
Department: BBA
Bob enrolled in 1 course(s):
BUS101
=========================
Name: Jon
Department: EEE
Bob enrolled in 2 course(s):
MAT110, PHY111

In [ ]:
#Task 21
class Student:
  def __init__(self,name,id,dept):
    self.name=name
    self.id=id
    self.dept=dept
  def details(self):
    return f'Name: {self.name}\nID: {self.id}\nDepartment: {self.dept}'
  def advise(self,*c):
    self.courses=''
    self.credits=0.0
    self.count=0
    for i in c:
      self.courses+=i+', '
      self.credits+=3.0
      self.count+=1
    if self.count<3:
      x=f'You have to take at least {3-self.count} more course.'
    elif self.count>4:
      x=f'You have to drop at least {self.count-4} course.'
    else:
      x='Ok'
    print(f'{self.name}, you have taken {self.credits} credits.')
    print(f'List of courses: {self.courses[:-2]}')
    print(f'Status: {x}')
s1 = Student("Alice", "20103012","CSE")
s2 = Student("Bob", "18301254","EEE")
s3 = Student("Carol", "17101238","CSE")
print("##########################")
print(s1.details())
print("##########################")
print(s2.details())
print("##########################")
s1.advise("CSE110", "MAT110", "PHY111")
print("##########################")
s2.advise("BUS101", "MAT120")
print("##########################")
s3.advise("MAT110", "PHY111", "ENG102", "CSE111", "CSE230")

##########################
Name: Alice
ID: 20103012
Department: CSE
##########################
Name: Bob
ID: 18301254
Department: EEE
##########################
Alice, you have taken 9.0 credits.
List of courses: CSE110, MAT110, PHY111
Status: Ok
##########################
Bob, you have taken 6.0 credits.
List of courses: BUS101, MAT120
Status: You have to take at least 1 more course.
##########################
Carol, you have taken 15.0 credits.
List of courses: MAT110, PHY111, ENG102, CSE111, CSE230
Status: You have to drop at least 1 course.

In [ ]:
#Task 22
class Hotel:
  def __init__(self,hotel_name):
    self.hotel_name=hotel_name
    self.stuff=0
    self.guest=0
    self.stuffs={}
    self.guests={}
  def addStuff(self,name,age=00,phone="000"):
    self.stuff+=1
    self.stuffs[self.stuff]=[name,age,phone]
    print(f'Staff With ID {self.stuff} is added')
  def addGuest(self,name,age=00,phone="000"):
    self.guest+=1
    self.guests[self.guest]=[name,age,phone]
    print(f'Guest With ID {self.guest} is created')
  def getStuffById(self,no):
    x=self.stuffs.get(no)
    return f'Staff ID: {no}\nName: {x[0]}\nAge: {x[1]}\nPhone no.: {x[2]}'
  def getGuestById(self,no):
    y=self.guests.get(no)
    return f'Staff ID: {no}\nName: {y[0]}\nAge: {y[1]}\nPhone no.: {y[2]}'
  def allStaffs(self):
    print('All Staffs:')
    print('Number of Staff:',len(self.stuffs))
    for i,j in self.stuffs.items():
      print(f'Staff ID: {i} Name: {j[0]} Age: {j[1]} Phone no: {j[2]}')
  def allGuest(self):
    print('All Guest:')
    print('Number of Guest:',len(self.guests))
    for i,j in self.guests.items():
      print(f'Guest ID: {i} Name: {j[0]} Age: {j[1]} Phone no.: {j[2]}')
h = Hotel("Lakeshore")
h.addStuff( "Adam", 26)
print("=================================")
print(h.getStuffById(1))
print("=================================")
h.addGuest("Carol",35,"123")
print("=================================")
print(h.getGuestById(1))
print("=================================")
h.addGuest("Diana", 32, "431")
print("=================================")
print(h.getGuestById(2))
print("=================================")
h.allStaffs()
print("=================================")
h.allGuest()

Staff With ID 1 is added
=================================
Staff ID: 1
Name: Adam
Age: 26
Phone no.: 000
=================================
Guest With ID 1 is created
=================================
Staff ID: 1
Name: Carol
Age: 35
Phone no.: 123
=================================
Guest With ID 2 is created
=================================
Staff ID: 2
Name: Diana
Age: 32
Phone no.: 431
=================================
All Staffs:
Number of Staff: 1
Staff ID: 1 Name: Adam Age: 26 Phone no: 000
=================================
All Guest:
Number of Guest: 2
Guest ID: 1 Name: Carol Age: 35 Phone no.: 123
Guest ID: 2 Name: Diana Age: 32 Phone no.: 431

In [ ]:
#Task 23
class Author:
  def __init__(self,name=None):
    self.name=name
    self.books={}
    self.bookcount=0
  def setName(self,name):
    self.name=name
  def addBook(self,title,genre):
    if self.name==None:
      print("A book can not be added without author name")
    else:
      self.bookcount+=1
      if genre not in self.books:
        self.books[genre]=title
      else:
        self.books[genre]+=", "+title
  def printDetail(self):
    print("Number of Book(s):",self.bookcount)
    print("Author Name:",self.name)
    for i, j in self.books.items():
      print(i+":",j)
a1 = Author()
print("=================================")
a1.addBook("Ice", "Science Fiction")
print("=================================")
a1.setName("Anna Kavan")
a1.addBook("Ice", "Science Fiction")
a1.printDetail()
print("=================================")
a2 = Author("Humayun Ahmed")
a2.addBook("Onnobhubon", "Science Fiction")
a2.addBook("Megher Upor Bari", "Horror")
print("=================================")
a2.printDetail()
a2.addBook("Ireena", "Science Fiction")
print("=================================")
a2.printDetail()
print("=================================")

=================================
A book can not be added without author name
=================================
Number of Book(s): 1
Author Name: Anna Kavan
Science Fiction: Ice
=================================
=================================
Number of Book(s): 2
Author Name: Humayun Ahmed
Science Fiction: Onnobhubon
Horror: Megher Upor Bari
=================================
Number of Book(s): 3
Author Name: Humayun Ahmed
Science Fiction: Onnobhubon, Ireena
Horror: Megher Upor Bari
=================================

In [ ]:
#Task 24
class Hospital:
  def __init__(self,name):
    self.name=name
    self.doctors={}
    self.patients={}
  def addDoctor(self,doctor):
    self.doctors[doctor.id]=[doctor.name,doctor.speciality]
  def getDoctorByID(self,id):
    if id in self.doctors:
      return f"Doctor's ID: {id}\nName: {self.doctors[id][0]}\nSpeciality: {self.doctors[id][1]}"
    else:
      return "Doctor not found"
  def allDoctors(self):
    print("All Doctors:")
    print("Number of Doctors:",len(self.doctors))
    print(self.doctors)
  def addPatient(self,patient):
    self.patients[patient.id]=[patient.name,patient.age,patient.phone]
  def getPatientByID(self,id):
    if id in self.patients:
      return f"Patient's ID: {id}\nName: {self.patients[id][0]}\nAge: {self.patients[id][1]}\nPhone no.: {self.patients[id][2]}"
    else:
      return "Patient not found"
  def allPatients(self):
    print("All Patients:")
    print("Number of Patients:",len(self.patients))
    print(self.patients)
class Doctor:
  def __init__(self,id,title,name,speciality):
    self.id=id
    self.title=title
    self.name=name
    self.speciality=speciality
class Patient:
  def __init__(self,id,title,name,age,phone):
    self.id=id
    self.title=title
    self.name=name
    self.age=age
    self.phone=phone
h = Hospital("Evercare")
d1 = Doctor("1d","Doctor", "Samar Kumar", "Neurologist")
h.addDoctor(d1)
print("=================================")
print(h.getDoctorByID("1d"))
print("=================================")
p1 = Patient("1p","Patient", "Kashem Ahmed", 35, 12345)
h.addPatient(p1)
print("=================================")
print(h.getPatientByID("1p"))
print("=================================")
p2 = Patient ("2p","Patient", "Tanina Haque", 26, 33456)
h.addPatient(p2)
print("=================================")
print(h.getPatientByID("2p"))
print("=================================")
h.allDoctors()
h.allPatients()

=================================
Doctor's ID: 1d
Name: Samar Kumar
Speciality: Neurologist
=================================
=================================
Patient's ID: 1p
Name: Kashem Ahmed
Age: 35
Phone no.: 12345
=================================
=================================
Patient's ID: 2p
Name: Tanina Haque
Age: 26
Phone no.: 33456
=================================
All Doctors:
Number of Doctors: 1
{'1d': ['Samar Kumar', 'Neurologist']}
All Patients:
Number of Patients: 2
{'1p': ['Kashem Ahmed', 35, 12345], '2p': ['Tanina Haque', 26, 33456]}

In [ ]:
#Task 25
class Vaccine:
  def __init__(self,name,country,interval):
    self.name=name
    self.country=country
    self.interval=interval
class Person:
  def __init__(self,name,age,ptype="General Citizen"):
    self.name=name
    self.age=age
    self.ptype=ptype
    self.vaccines=[]
    self.dose1=False
    self.dose2=False
  def pushVaccine(self,vaccine,dose='1st Dose'):
    self.vaccine_name=vaccine.name
    self.vaccine_interval=vaccine.interval
    self.dose=dose
    if self.age<25 and self.ptype!='Student':
      print(f'Sorry {self.name}, Minimum age for taking vaccines is 25 years now.')
    elif self.age>=25 and self.ptype!='Student' and self.dose=='1st Dose':
      print('1st dose done for',self.name)
      self.dose1=True
      self.vaccines.append(vaccine)
    elif self.ptype=='Student' and self.dose=='1st Dose':
      print('1st dose done for',self.name)
      self.dose1=True
      self.vaccines.append(vaccine)
    elif self.dose=='2nd Dose' and self.vaccines[-1]!=vaccine:
      print(f'Sorry {self.name}, you can’t take 2 different vaccines')
    else:
      print('2nd dose done for',self.name)
      self.dose2=True
      self.vaccines.append(vaccine)
  def showDetail(self):
    print(f'Name: {self.name} Age: {self.age} Type: {self.ptype}')
    print('Vaccine name:',self.vaccine_name)
    if self.dose1==True and self.dose2==False:
      print('1st dose: Given')
      print(f'2nd dose: Please come after {self.vaccine_interval} days')
    elif self.dose1==True and self.dose2==True:
      print('1st dose: Given')
      print('2nd dose: Given')
    else:
      print('1st dose: Not Given')
      print('2nd dose: Not Given')
astra = Vaccine("AstraZeneca", "UK", 60)
modr = Vaccine("Moderna", "UK", 30)
sin = Vaccine("Sinopharm", "China", 30)
p1 = Person("Bob", 21, "Student")
print("=================================")
p1.pushVaccine(astra)
print("=================================")
p1.showDetail()
print("=================================")
p1.pushVaccine(sin, "2nd Dose")
print("=================================")
p1.pushVaccine(astra, "2nd Dose")
print("=================================")
p1.showDetail()
print("=================================")
p2 = Person("Carol", 23, "Actor")
print("=================================")
p2.pushVaccine(sin)
print("=================================")
p3 = Person("David", 34)
print("=================================")
p3.pushVaccine(modr)
print("=================================")
p3.showDetail()
print("=================================")
p3.pushVaccine(modr, "2nd Dose")

=================================
1st dose done for Bob
=================================
Name: Bob Age: 21 Type: Student
Vaccine name: AstraZeneca
1st dose: Given
2nd dose: Please come after 60 days
=================================
Sorry Bob, you can’t take 2 different vaccines
=================================
2nd dose done for Bob
=================================
Name: Bob Age: 21 Type: Student
Vaccine name: AstraZeneca
1st dose: Given
2nd dose: Given
=================================
=================================
Sorry Carol, Minimum age for taking vaccines is 25 years now.
=================================
=================================
1st dose done for David
=================================
Name: David Age: 34 Type: General Citizen
Vaccine name: Moderna
1st dose: Given
2nd dose: Please come after 30 days
=================================
2nd dose done for David